## PROYECTO DE ANÁLISIS DE DATOS DE FÚTBOL
### ASIGNATURA: MACHINE LEARNING
#### Autores: Manuel García Romero y Rafael Delgado Martínez

In [1]:
from statsbombpy import sb

In [5]:
comps = sb.competitions()
comps.info()
comps.head()

credentials were not supplied. open data access only
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   competition_id             40 non-null     int64
 1   season_id                  40 non-null     int64
 2   country_name               40 non-null     object
 3   competition_name           40 non-null     object
 4   competition_gender         40 non-null     object
 5   competition_youth          40 non-null     bool
 6   competition_international  40 non-null     bool
 7   season_name                40 non-null     object
 8   match_updated              39 non-null     object
 9   match_updated_360          39 non-null     object
 10  match_available_360        2 non-null      object
 11  match_available            39 non-null     object
dtypes: bool(2), int64(2), object(8)
memory usage: 3.3+ KB

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,16,4,Europe,Champions League,male,False,False,2018/2019,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-07-09T14:06:05.802
1,16,1,Europe,Champions League,male,False,False,2017/2018,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-01-23T21:55:30.425330
2,16,2,Europe,Champions League,male,False,False,2016/2017,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
3,16,27,Europe,Champions League,male,False,False,2015/2016,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
4,16,26,Europe,Champions League,male,False,False,2014/2015,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00

In [27]:
m = sb.matches(43,3)
m = m[m['away_team'] == 'Spain']
m

credentials were not supplied. open data access only

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_stage,stadium,referee,data_version,shot_fidelity_version,xy_fidelity_version
8,7576,2018-06-15,20:00:00.000,International - FIFA World Cup,2018,Portugal,Spain,3,3,available,scheduled,2021-12-06T22:30:32.372616,2021-06-13T16:17:31.694,1,Group Stage,Olimpiyskiy Stadion Fisht,Gianluca Rocchi,1.0.2,None,None
44,7543,2018-06-20,20:00:00.000,International - FIFA World Cup,2018,Iran,Spain,0,1,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,2,Group Stage,Kazan' Arena (Kazan'),Andrés Cunha,1.0.2,None,None

In [6]:
match_events = sb.events(7576)

'''match_events.columns
match_events = match_events[['team','type','minute','location','pass_end_location','player']]
match_events = match_events[match_events['type']=='Pass']
match_events.head(30)'''

credentials were not supplied. open data access only

"match_events.columns\nmatch_events = match_events[['team','type','minute','location','pass_end_location','player']]\nmatch_events = match_events[match_events['type']=='Pass']\nmatch_events.head(30)"

In [10]:
print([match_events['play_pattern']])

[0         Regular Play
1         Regular Play
2         Regular Play
3         Regular Play
4          From Corner
             ...
4149    From Free Kick
4150    From Free Kick
4151      Regular Play
4152    From Free Kick
4153    From Free Kick
Name: play_pattern, Length: 4154, dtype: object]

In [ ]:
'''ANGULO DE PASE 0 SI ES HACIA LA PORTERIA CONTRARIA. VALOR MEJORA SI MÁS CERCANO A 0. -pi a pi, en radianes

COLUMNA ASSISTED_SHOT_ID/SHOT_ASSIST OR GOAL-ASSIST -> SI EL PASE ACABA ASISTE UN TIRO

OUTCOME VACIO (PASE COMPLETADO)

END LOCATION -> DÓNDE ACABA EL BALÓN.'''